name: Bug
description: File a bug report
title: "Bug report"
labels: ["bug"]
assignees:
  - hinell
body:
  - type: checkboxes
    id: issue-trouble-is-read
    attributes:
      label: I've read TROUBLESHOOTING](../blob/main/doc/index.md#TROUBLESHOOTING) instructions
      options:
        - label: "Yes"
          required: true
  - type: textarea
    id: issue-summary
    attributes:
      label: Summary
      placeholder: "Be brief, time is invaluable commodity that only few can afford"
    validations:
      required: true
  - type: textarea
    id: issue-repro
    attributes:
      label: Steps to reproduce
      placeholder: Specify how to reproduce issue if there are any ways
    validations:
      required: false
  - type: textarea
    id: issue-checkhealth 
    attributes:
      label: checkhealth output
      placeholder: Run `checkhealth lsp-timeout` and paste
    validations:
      required: true 
  - type: textarea
    id: issue-env
    attributes:
      label: Versions
      placeholder: |
        Specify all relevant VERSIONS and commits, e.g.:
        NVIM v0.10.0-dev-ac1c23442f
        Build type: MinSizeRel
        LuaJIT 2.1.0-beta3
    validations:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: Specify operating system/environment
      options:
        - Linux/Debian/Ubuntu
        - Linux/Debian/Kubuntu
        - Linxu/Archlinux
        - Linux/NixOS
        - Linux/Other
        - MacOS
        - Windows
        - Windows WSL
        - Docker
        - Other
    validations:
      required: true
