# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature
description: "File a feature request; they are aren't expected, but you can try"
labels: ["enhancement"]
assignees:
  - hinell
body:
  - type: markdown
    attributes:
      value: "Please, see [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) first, then, checkout [DISCUSSIONS](../discussions)"
  - type: textarea
    id: feature-summary
    attributes:
      label: Summary
      placeholder: "Be brief, time is invaluable commodity that only few can afford"
